### ISSUE TITLE
Better handling code block

### ISSUE THREAD

**Issue by yujonglee** [letmutex/htmd#14]
https://github.com/letmutex/htmd/blob/main/src/element_handler/code.rs

Seems like built-in code tag handler only consider class attribute in code tag.

However, for both `prismjs` and `highlightjs`, the actual structure is

```html
<pre class="language-rs"><code>CONTENT</code></pre>
```

To support this, I guess we need to modify handler interface.

**Comment by letmutex** [comment]
Thanks for reporting this.

It should not be difficult to access the attrs of the parent node using the current tag handler, will open a PR later.

**Comment by letmutex** [comment]
Done in v0.1.5

https://github.com/letmutex/htmd/releases/tag/v0.1.5
