### ISSUE TITLE
Send/Sync impls are wrong

### ISSUE THREAD

**Issue by lukaslueg** [letmutex/htmd#16]
https://github.com/letmutex/htmd/blob/0579eeabfc61fd2066f4e634d87d13403c7b7de8/src/element_handler/mod.rs#L50

Note that the `Send`/`Sync` impls are unjustified and wrong: It is always possible to come up with a `impl ElementHandler for T` where `T` is not `Send`/`Sync`.

**Comment by letmutex** [comment]
Thanks for pointing this out! Making `Send` and `Sync` the supertraits of `ElementHandler`.
