### ISSUE TITLE
Implement a command-line utility

### ISSUE THREAD

**Issue by dbohdan** [letmutex/htmd#2]
This would be useful in and of itself and would simplify evaluating the library before one adopts it.

**Comment by letmutex** [comment]
Good idea! might do this later.

**Comment by tgy** [comment]
Also this would be great to process HTML emails to read them in a terminal using something like neomutt. I'd like to try it out for that purpose.

**Comment by dbohdan** [comment]
@tgy Note that you can already read HTML emails in NeoMutt. Try https://www.schabell.org/2009/08/display-and-read-html-mail-with-mutt.html.

For Markdown, you can use Pandoc in the `.mailcap` file with something like

    text/html;      pandoc --from html --to markdown; copiousoutput

A big problem with this is that HTML emails often use old-school [table layouts](https://thehistoryoftheweb.com/tables-layout-absurd/). Converting them to Markdown gives you Markdown tables (depending on the dialect). `links -dump` output like in the blog post I linked at the beginning is more readable for tables.

**Comment by tgy** [comment]
@dbohdan thanks! i'm aware of existing solutions for converting html emails to markdown, and i've tried using pandoc for that in the past. the reason why i'm interested in htmd is its rust implem and its speed. pandoc can be slow, making the UX of reading emails not great because you have to wait for the email markdown text to load

**Comment by dbohdan** [comment]
@tgy Ah, I see. You're welcome. Once there is an HTMD CLI, I would like to benchmark it against Pandoc.

I have tried both Pandoc and Links for NeoMutt `auto_view`. `links -dump` was faster for me: no noticeable delay on a budget VPS, when with `pandoc --from html --to markdown` there was.

I have also now discovered [suntong/html2md](/suntong/html2md). I'll benchmark it later, too.

**Comment by letmutex** [comment]
[htmd-cli](https://github.com/letmutex/htmd-cli) is out! Feel free to try!

**Comment by dbohdan** [comment]
Here is the benchmark I promised. htmd-cli comes ahead of both Pandoc and html2md.

## Source code

```shell
#! /bin/sh
# A simple benchmark script comparing htmd, html2md, and Pandoc.
# Requires those programs plus cURL and hyperfine.
#
# https://github.com/sharkdp/hyperfine
# https://github.com/letmutex/htmd-cli
# https://github.com/suntong/html2md
# https://pandoc.org
#
# License: Apache License 2.0 like htmd.

set -eu

hyperfine --version
printf 'htmd %s\n' "$(htmd --version)"
printf 'html2md %s\n' "$(html2md | grep Version)"
pandoc --version | head -n 1
echo ''

# Download a fairly large text-heavy HTML page for testing.
curl \
    --fail \
    --location \
    --output tank.html \
    --silent \
    https://gwern.net/tank \
    ;

hyperfine \
    --shell none \
    --warmup 10 \
    'pandoc --from html --to commonmark_x tank.html' \
    'html2md -i tank.html' \
    'htmd tank.html' \
    ;
```

## Output

```none
hyperfine 1.18.0
htmd 0.3.0
html2md Version 1.5.0 built on 2024-02-10
pandoc 3.1.13

Benchmark 1: pandoc --from html --to commonmark_x tank.html
  Time (mean ± σ):     513.5 ms ±  11.6 ms    [User: 459.7 ms, System: 49.8 ms]
  Range (min … max):   487.6 ms … 527.3 ms    10 runs
 
Benchmark 2: html2md -i tank.html
  Time (mean ± σ):      32.4 ms ±   0.6 ms    [User: 36.3 ms, System: 5.9 ms]
  Range (min … max):    31.5 ms …  35.5 ms    93 runs
 
Benchmark 3: htmd tank.html
  Time (mean ± σ):      10.6 ms ±   0.6 ms    [User: 8.1 ms, System: 2.9 ms]
  Range (min … max):    10.2 ms …  19.7 ms    286 runs
 
Summary
  htmd tank.html ran
    3.04 ± 0.19 times faster than html2md -i tank.html
   48.23 ± 3.13 times faster than pandoc --from html --to commonmark_x tank.html
```
